export const Step = {
  UNTAP: "UNTAP",
  UPKEEP: "UPKEEP",
  DRAW: "DRAW",
  FIRST_MAIN: "FIRST_MAIN",
  BEGINNING_OF_COMBAT: "BEGINNING_OF_COMBAT",
  DECLARE_ATTACKERS: "DECLARE_ATTACKERS",
  DECLARE_BLOCKERS: "DECLARE_BLOCKERS",
  COMBAT_DAMAGE: "COMBAT_DAMAGE",
  END_OF_COMBAT: "END_OF_COMBAT",
  SECOND_MAIN: "SECOND_MAIN",
  END_STEP: "END_STEP",
  CLEANUP: "CLEANUP",
} as const

export type GameSteps = (typeof Step)[keyof typeof Step]
