//! CK1 Regenerate keyword integration tests.
//!
//! These tests exercise the full CK1 pipeline:
//!   River Troll activated ability → stack → resolution → regeneration shield →
//!   lethal damage/destroy → SBA → creature survives (tapped, damage cleared).
//!
//! All tests use the public API of `echomancy-core`.
//!
//! Test scenarios:
//!   ck1_1 — Regenerate saves creature from lethal damage (via SBA path)
//!   ck1_2 — Regenerate saves creature from destroy effect
//!   ck1_3 — Zero toughness bypasses regeneration (CR 704.5f)
//!   ck1_4 — Regenerate shield is consumed after one use
//!   ck1_5 — Multiple regenerate activations stack shields

use echomancy_core::prelude::*;

// ============================================================================
// Shared setup helpers
// ============================================================================

/// Create a 2-player game advanced to P1's FirstMain step.
///
/// P1 has a Forest on the battlefield so {G} can be generated by tapping it.
fn make_ck1_game() -> (Game, String, String) {
    let p1 = "p1".to_owned();
    let p2 = "p2".to_owned();

    let mut game = Game::create("ck1-test");
    game.add_player(&p1, "Alice").unwrap();
    game.add_player(&p2, "Bob").unwrap();

    // Minimal decks — enough to avoid decking out during setup.
    let p1_deck: Vec<CardInstance> = (0..10)
        .map(|i| CardInstance::new(format!("p1-lib-{i}"), catalog::forest(), &p1))
        .collect();
    let p2_deck: Vec<CardInstance> = (0..10)
        .map(|i| CardInstance::new(format!("p2-lib-{i}"), catalog::mountain(), &p2))
        .collect();
    game.assign_deck(&p1, p1_deck).unwrap();
    game.assign_deck(&p2, p2_deck).unwrap();

    game.start(&p1, Some(42)).unwrap();

    // Advance: Untap → Upkeep → Draw → FirstMain.
    while game.current_step() != Step::FirstMain {
        let current = game.current_player_id().to_owned();
        game.apply(Action::AdvanceStep {
            player_id: PlayerId::new(&current),
        })
        .expect("should be able to advance to FirstMain");
    }

    assert_eq!(game.current_step(), Step::FirstMain);

    (game, p1, p2)
}

/// Add a River Troll (2/3) to P1's battlefield, returning the instance ID.
fn add_river_troll(game: &mut Game, player_id: &str, instance_id: &str) {
    let troll = CardInstance::new(instance_id, catalog::river_troll(), player_id);
    game.add_permanent_to_battlefield(player_id, troll)
        .expect("should be able to add River Troll to battlefield");
}

/// Add a Forest and tap it to generate {G} for P1.
///
/// Returns the forest instance ID (unique per call, pass in a unique suffix).
fn tap_forest_for_green(game: &mut Game, player_id: &str, forest_id: &str) {
    let forest = CardInstance::new(forest_id, catalog::forest(), player_id);
    game.add_permanent_to_battlefield(player_id, forest)
        .expect("should be able to add Forest");
    game.apply(Action::ActivateAbility {
        player_id: PlayerId::new(player_id),
        permanent_id: CardInstanceId::new(forest_id),
        ability_index: 0,
    })
    .expect("should be able to tap Forest for {G}");
}

/// Activate the River Troll's regenerate ability ({G}) and resolve the stack.
///
/// After activation, priority passes to p2 first (non-mana ability).
/// Both players pass to let the ability resolve.
fn activate_and_resolve_regenerate(
    game: &mut Game,
    troll_id: &str,
    p1: &str,
    p2: &str,
) {
    game.apply(Action::ActivateAbility {
        player_id: PlayerId::new(p1),
        permanent_id: CardInstanceId::new(troll_id),
        ability_index: 0,
    })
    .expect("should be able to activate regenerate ability");

    // After a non-mana activation, priority goes to the opponent first.
    game.apply(Action::PassPriority { player_id: PlayerId::new(p2) })
        .expect("p2 should be able to pass priority");
    game.apply(Action::PassPriority { player_id: PlayerId::new(p1) })
        .expect("p1 should be able to pass priority after p2");

    assert!(game.stack().is_empty(), "stack should be empty after regenerate resolves");
}

// ============================================================================
// CK1.1 — Regenerate saves creature from lethal damage (via SBA)
// ============================================================================

/// CK1.1: River Troll (2/3) has {G} available. Player activates regenerate,
///        ability resolves, shield is registered. Then 4 damage is dealt (lethal
///        for 3-toughness). SBA runs — regen shield fires.
///   - Verify: Troll is still on battlefield.
///   - Verify: Troll is tapped (CR 701.15a).
///   - Verify: Troll has 0 damage marked (cleared by regeneration).
///   - Verify: Regeneration shield is consumed.
#[test]
fn ck1_1_regenerate_saves_creature_from_lethal_damage() {
    let (mut game, p1, p2) = make_ck1_game();

    add_river_troll(&mut game, &p1, "troll-1");
    tap_forest_for_green(&mut game, &p1, "forest-ck1-1");
    activate_and_resolve_regenerate(&mut game, "troll-1", &p1, &p2);

    assert!(
        game.has_regeneration_shield("troll-1"),
        "regeneration shield should be registered after ability resolves"
    );

    // Deal 4 damage — lethal for a 2/3 (4 >= 3 toughness).
    let _ = game.deal_damage_to_creature("troll-1", 4);

    // Verify the damage is marked before SBA.
    let state_before = game.permanent_state("troll-1").expect("troll should exist before SBA");
    let cs_before = state_before.creature_state().expect("troll should have creature state");
    assert_eq!(cs_before.damage_marked_this_turn(), 4, "troll should have 4 damage marked before SBA");

    // Run SBA — lethal damage triggers destroy, regen shield intercepts.
    game.run_sba();

    // Troll should still be on battlefield.
    let on_bf = game
        .battlefield(&p1)
        .unwrap()
        .iter()
        .any(|c| c.instance_id() == "troll-1");
    assert!(on_bf, "River Troll should still be on battlefield after regeneration fires");

    // Troll should NOT be in graveyard.
    let in_gy = game
        .graveyard(&p1)
        .unwrap()
        .iter()
        .any(|c| c.instance_id() == "troll-1");
    assert!(!in_gy, "River Troll should NOT be in graveyard after regeneration fires");

    // Troll should be tapped (CR 701.15a).
    let state_after = game.permanent_state("troll-1").expect("troll state should exist");
    assert!(
        state_after.is_tapped(),
        "River Troll should be tapped after regeneration fires (CR 701.15a)"
    );

    // Troll should have 0 damage marked (cleared by regeneration).
    let cs_after = state_after.creature_state().expect("troll should have creature state");
    assert_eq!(
        cs_after.damage_marked_this_turn(),
        0,
        "River Troll should have 0 damage after regeneration cleared it (CR 701.15a)"
    );

    // Regeneration shield should be consumed.
    assert!(
        !game.has_regeneration_shield("troll-1"),
        "regeneration shield should be consumed after firing"
    );
}

// ============================================================================
// CK1.2 — Regenerate saves creature from a destroy effect
// ============================================================================

/// CK1.2: River Troll has a regen shield active. A destroy effect (simulated
///        via test helper) is applied. The shield intercepts the destroy.
///   - Verify: Troll survives and is tapped.
///   - Verify: Shield is consumed.
#[test]
fn ck1_2_regenerate_saves_creature_from_destroy_effect() {
    let (mut game, p1, p2) = make_ck1_game();

    add_river_troll(&mut game, &p1, "troll-2");
    tap_forest_for_green(&mut game, &p1, "forest-ck1-2");
    activate_and_resolve_regenerate(&mut game, "troll-2", &p1, &p2);

    assert!(
        game.has_regeneration_shield("troll-2"),
        "regen shield should be registered before destroy"
    );

    // Simulate a destroy effect via deal_damage_to_creature (lethal) + run_sba.
    // The destroy path through SBA is the same whether from damage or from
    // a destroy spell (both call move_permanent_to_graveyard_with_reason with
    // DestroyReason — the regen shield intercepts the destroy event).
    let _ = game.deal_damage_to_creature("troll-2", 10); // clearly lethal
    game.run_sba();

    // Troll should still be on battlefield.
    let on_bf = game
        .battlefield(&p1)
        .unwrap()
        .iter()
        .any(|c| c.instance_id() == "troll-2");
    assert!(on_bf, "Troll should survive after regeneration intercepts the destroy");

    // Troll should be tapped.
    let state = game.permanent_state("troll-2").expect("troll should exist");
    assert!(state.is_tapped(), "Troll should be tapped after regeneration");

    // Shield consumed.
    assert!(
        !game.has_regeneration_shield("troll-2"),
        "shield should be consumed after firing"
    );
}

// ============================================================================
// CK1.3 — Zero toughness bypasses regeneration (CR 704.5f)
// ============================================================================

/// CK1.3: River Troll has a regen shield. A Layer 7b effect sets toughness to 0.
///        SBA runs — zero-toughness uses "put into graveyard", not "destroy",
///        so the regen shield does NOT intercept (CR 704.5f).
///   - Verify: Troll goes to graveyard despite regen shield.
///   - Verify: Shield is cleaned up (source left battlefield).
#[test]
fn ck1_3_zero_toughness_bypasses_regeneration() {
    let (mut game, p1, p2) = make_ck1_game();

    add_river_troll(&mut game, &p1, "troll-3");
    tap_forest_for_green(&mut game, &p1, "forest-ck1-3");
    activate_and_resolve_regenerate(&mut game, "troll-3", &p1, &p2);

    assert!(
        game.has_regeneration_shield("troll-3"),
        "regen shield should be registered before zero-toughness SBA"
    );

    // Inject a Layer 7b effect that sets P/T to 2/0 (zero toughness).
    game.inject_set_pt_effect("troll-3", 2, 0);

    assert_eq!(
        game.effective_toughness("troll-3"),
        Some(0),
        "effective toughness should be 0 after Layer 7b effect"
    );

    // Run SBA — zero toughness fires CR 704.5f "put into graveyard" (not destroy).
    game.run_sba();

    // Troll should be in graveyard (zero toughness bypasses regen).
    let in_gy = game
        .graveyard(&p1)
        .unwrap()
        .iter()
        .any(|c| c.instance_id() == "troll-3");
    assert!(
        in_gy,
        "Troll should be in graveyard — zero toughness bypasses regeneration (CR 704.5f)"
    );

    // Troll should NOT be on battlefield.
    let on_bf = game
        .battlefield(&p1)
        .unwrap()
        .iter()
        .any(|c| c.instance_id() == "troll-3");
    assert!(!on_bf, "Troll should NOT be on battlefield after zero-toughness SBA");

    // Shield cleaned up when source leaves battlefield.
    assert!(
        !game.has_regeneration_shield("troll-3"),
        "regen shield should be cleaned up when source leaves battlefield"
    );
}

// ============================================================================
// CK1.4 — Regenerate shield is consumed after one use
// ============================================================================

/// CK1.4: Activate regenerate once — shield fires on first lethal damage event.
///        After that, a second lethal damage event kills the troll (no shield left).
///   - Verify: Troll survives the first lethal damage.
///   - Verify: Troll dies on the second lethal damage.
#[test]
fn ck1_4_regenerate_shield_is_consumed_after_one_use() {
    let (mut game, p1, p2) = make_ck1_game();

    add_river_troll(&mut game, &p1, "troll-4");
    tap_forest_for_green(&mut game, &p1, "forest-ck1-4");
    activate_and_resolve_regenerate(&mut game, "troll-4", &p1, &p2);

    assert!(game.has_regeneration_shield("troll-4"), "shield should be registered");

    // First lethal damage — shield fires.
    let _ = game.deal_damage_to_creature("troll-4", 4);
    game.run_sba();

    let on_bf_first = game
        .battlefield(&p1)
        .unwrap()
        .iter()
        .any(|c| c.instance_id() == "troll-4");
    assert!(on_bf_first, "Troll should survive first lethal damage (shield fires)");
    assert!(!game.has_regeneration_shield("troll-4"), "shield should be consumed after first use");

    // Second lethal damage — no shield left.
    let _ = game.deal_damage_to_creature("troll-4", 4);
    game.run_sba();

    let in_gy = game
        .graveyard(&p1)
        .unwrap()
        .iter()
        .any(|c| c.instance_id() == "troll-4");
    assert!(in_gy, "Troll should die on second lethal damage (shield consumed)");

    let on_bf_second = game
        .battlefield(&p1)
        .unwrap()
        .iter()
        .any(|c| c.instance_id() == "troll-4");
    assert!(!on_bf_second, "Troll should NOT be on battlefield after dying to second lethal damage");
}

// ============================================================================
// CK1.5 — Multiple regenerate activations stack shields
// ============================================================================

/// CK1.5: Activate regenerate twice on the same creature — two shields are stacked.
///        Both lethal damage events are intercepted in sequence.
///   - Verify: Troll survives the first lethal damage (first shield fires).
///   - Verify: Troll survives the second lethal damage (second shield fires).
///   - Verify: After two uses, no shields remain.
#[test]
fn ck1_5_multiple_regenerate_activations_stack_shields() {
    let (mut game, p1, p2) = make_ck1_game();

    add_river_troll(&mut game, &p1, "troll-5");

    // First regenerate activation.
    tap_forest_for_green(&mut game, &p1, "forest-ck1-5a");
    activate_and_resolve_regenerate(&mut game, "troll-5", &p1, &p2);

    // Second regenerate activation.
    tap_forest_for_green(&mut game, &p1, "forest-ck1-5b");
    activate_and_resolve_regenerate(&mut game, "troll-5", &p1, &p2);

    assert_eq!(
        game.replacement_effect_count(),
        2,
        "two regeneration shields should be stacked"
    );

    // First lethal damage — first shield fires.
    let _ = game.deal_damage_to_creature("troll-5", 5);
    game.run_sba();

    let on_bf_first = game
        .battlefield(&p1)
        .unwrap()
        .iter()
        .any(|c| c.instance_id() == "troll-5");
    assert!(on_bf_first, "Troll should survive first lethal damage (first shield fires)");
    assert_eq!(
        game.replacement_effect_count(),
        1,
        "one shield should remain after first use"
    );

    // Second lethal damage — second shield fires.
    let _ = game.deal_damage_to_creature("troll-5", 5);
    game.run_sba();

    let on_bf_second = game
        .battlefield(&p1)
        .unwrap()
        .iter()
        .any(|c| c.instance_id() == "troll-5");
    assert!(on_bf_second, "Troll should survive second lethal damage (second shield fires)");
    assert_eq!(
        game.replacement_effect_count(),
        0,
        "both shields should be consumed after two uses"
    );
}
